services:
  db:  
    image: postgres:13
    container_name: dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: triviagame_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - app_network
  app:
    build: 
      context: .
      dockerfile: dockerfile.dev
    depends_on:
      - db
    container_name: trivia_app
    ports:
      - "8080:8080"
    environment:
      - FLASK_SECRET_KEY
      - DATABASE_PUBLIC_URL
      - FLASK_APP=trivia_game.py  
    command: bash -c "flask db upgrade && python trivia_game.py"
    networks:
    - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge