version: '3.8'

services:
  db:
    image: postgres:13
    container_name: dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: triviagame_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data_import:
    build:
      context: .
      dockerfile: Dockerfile  # We will define a simple Dockerfile to run the script
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_db_user:your_db_password@db:5432/your_db_name
    command: python import_data.py  # Run the data import script when the container starts
    volumes:
      - ./import_data.py:/app/import_data.py  # Mount your Python script to the container
      - ./data.json:/app/data.json  # Mount your data file (if using a local file)

  # Other services (e.g., your application) can go here

volumes:
  postgres_data:
    driver: local

