"""Add nullable password field

Revision ID: 261f626d7c5c
Revises: 372f254170ff
Create Date: 2025-03-07 11:31:26.063108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261f626d7c5c'
down_revision = '372f254170ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
