"""Added score column

Revision ID: 372f254170ff
Revises: 3301b6d27dba
Create Date: 2025-03-06 21:26:28.055640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372f254170ff'
down_revision = '3301b6d27dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
